Dsin_Valbernielsons_hamburgueria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

app_name = 'core'
urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^login/$', auth_views.LoginView.as_view(), {'redirect_field_name': 'home'}, name='login'),
    url(r'^logout/$', auth_views.logout_then_login,  {"login_url": "ham:home"}, name='logout'),
    url(r'^', include('Hamburgueria.urls')),
]

Hamburgueria/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'ham'
urlpatterns = [
    url(r'^finaliza/', views.fechaProduto, name='finaliza'),
    url(r'^cancela/(?P<pk>\d+)$', views.cancelaPedido, name='cancela'),
    url(r'^remove/(?P<pk>\d+)$', views.removeProduto, name='remove'),
    url(r'^adiciona/(?P<pk>\d+)$', views.addProduto, name='adicionar'),
    url(r'^pedidos/', views.pedidos, name='pedidos'),
    url(r'^', views.home, name='home'),
]

Hamburgueria/models.py
from django.db import models
from django.core.validators import MinValueValidator


class Pedido(models.Model):
    STATUSES = (
        ('P', 'Pedido Efetuado'),
        ('A', 'Em Andamento'),
        ('E', 'Entregando'),
        ('X', 'Entregue'),
        ('C', 'Carrinho'),
    )
    status_pedido = models.CharField(max_length=1, choices=STATUSES, default='P')
    owner = models.ForeignKey('auth.User', related_name='pedidos', on_delete=models.CASCADE)
    data = models.DateTimeField(auto_now_add=True)
    # status_pedido = models.BooleanField(default=False)

    def __str__(self):
        return 'Pedido nr' + str(self.id) + ' de ' + str(self.owner)

    class Meta:
        verbose_name = ("Pedido")
        verbose_name_plural = ("Pedidos")


class Produto(models.Model):
    FOOD_CATEGORY = (
        ('L', 'Lanches'),
        ('B', 'Bebidas'),
        ('S', 'Sobremesas'),
    )
    categoria = models.CharField(max_length=1, choices=FOOD_CATEGORY)
    nome = models.CharField(max_length=200)
    preco = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.CharField(max_length=800, default='')


    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = ("Produto")
        verbose_name_plural = ("Produtos")


class ProdutoPedido(models.Model):
    pedido = models.ForeignKey(Pedido, related_name='Pedido', on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, related_name='Produto', on_delete=models.CASCADE)
    qtd = models.PositiveIntegerField(validators=[MinValueValidator(1)], default=1)

    def __str__(self):
        return 'Pedido nr:' +  str(self.pedido.id) + ' produto ' + str(self.produto)

    class Meta:
        verbose_name = ("ProdutoPedidos")
        verbose_name_plural = ("ProdutosPedido")


class Carrinho(models.Model):
    owner = models.ForeignKey('auth.User', related_name='CarrinhoItem', on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, related_name='Carrinho', on_delete=models.CASCADE)
    qtd = models.IntegerField(default=1)

Hamburgueria/views.py
from Hamburgueria.models import Produto, Pedido, ProdutoPedido, Carrinho
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q
from django.db.models import Sum


def home(request):
    context= {}
    context['usr'] = request.user.is_authenticated
    context['staff'] = request.user.is_staff
    context['produtos'] = Produto.objects.all()
    if request.user.is_authenticated:
        context['carrinho'] = Carrinho.objects.filter(owner=request.user).aggregate(Sum('qtd'))['qtd__sum']
        context['listaCarrinho'] = Carrinho.objects.filter(owner=request.user)
    return render(request, 'Hamburgueria/homeCli.html', context)


def pedidos(request):
    context = {}
    context['carrinho'] = Carrinho.objects.filter(owner=request.user).aggregate(Sum('qtd'))['qtd__sum']
    context['listaCarrinho'] = Carrinho.objects.filter(owner=request.user)
    context['usr'] = request.user.is_authenticated
    context['staff'] = request.user.is_staff
    if request.user.is_authenticated:
        historico = Pedido.objects.filter(owner_id=request.user.id)
        produtos = ProdutoPedido.objects.filter(pedido__owner_id=request.user.id)
        context['historico'] = historico
        context['produtos'] = produtos
    return render(request, 'Hamburgueria/pedidos.html', context)


def detalhes(request):
    context = {}
    context['usr'] = request.user.is_authenticated
    context['staff'] = request.user.is_staff
    pk = request.data['pk']
    if request.user.is_authenticated:
        pedido = ProdutoPedido.objects.filter(pedido__id=pk)
        context['pedido'] = pedido
    return render(request, 'Hamburgueria/pedidos.html', context)


def addProduto(request, pk):
    produto = Carrinho.objects.filter(Q(owner=request.user), Q(produto=pk))
    prod = Produto.objects.get(pk=pk)
    if len(produto):
        produto = produto[0]
        produto.qtd += 1
        produto.save()
    else:
        Carrinho.objects.create(produto=prod, qtd=1, owner_id=request.user.id)
    return redirect('ham:home')


def fechaProduto(request):
    carrinho = Carrinho.objects.filter(owner=request.user.id)
    if carrinho:
        pedido = Pedido.objects.create(owner=request.user)
        for item in carrinho:
            prodPedido = ProdutoPedido.objects.create(pedido=pedido, produto_id=item.produto.id, qtd=item.qtd)
            item.delete()
    return redirect('ham:home')


def removeProduto(request, pk):
    produto = Carrinho.objects.filter(Q(owner=request.user), Q(produto=pk))
    produto.delete()
    return redirect('ham:home')


def cancelaPedido(request, pk):
    prodPedido = ProdutoPedido.objects.filter(pedido=pk)
    pedido = Pedido.objects.get(pk=pk)
    if prodPedido:
        for item in prodPedido:
            carrinho = Carrinho.objects.create(owner=request.user, produto=item.produto, qtd=item.qtd)
            item.delete()
    pedido.delete()
    return redirect('ham:pedidos')

Hamburgueria/templates/Hamburgueria/homeCli.html
{% extends 'base/base.html' %}
{% load staticfiles%}
{% load static %}

{% block title %} Home {% endblock %}

{% block style %}{% endblock %}

{% block body %}
    {%  include 'base/_navbar.html' %}
    <br><br><br><br>

    <div class="container marketing">
      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            {% for produto in produtos %}
              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                  <img class="card-img-top" src="{{ produto.image }}" alt="Card image {{ produto.nome }}">
                  <div class="card-body">
                    <p class="card-text">{{ produto.nome }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                                              {% if usr %}

                      <div class="btn-group">
                        <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'ham:adicionar' produto.id %}">Adicionar</a>
                      </div>
                                              {% endif %}

                      <small class="text-muted">R$ {{ produto.preco }}</small>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div><!-- /Container end -->
      </div>
    </div>
{%  endblock %}

Hamburgueria/templates/Hamburgueria/homeStaff.html
{% extends 'base/base.html' %}
{% load staticfiles%}
{% load static %}

{% block title %} Home {% endblock %}

{% block style %}{% endblock %}

{% block body %}
    {%  include 'base/_navbar.html' %}



    <p>Listagem Produtos</p>
    {% for produto in produtos %}


        {{ produto.categoria}}
        {{ produto.image}}
        {{ produto.nome}}
        {{ produto.preco}}

    {% endfor %}

    <p>Pedidos</p>

    {% for pedido in pedidos %}

        <h1>New Produto</h1>
        <p>{{ pedido.produto.preco }}</p>
        <p>{{ pedido.produto.nome }}</p>
        <p>{{ pedido.produto.image }}</p>
        <p>{{ pedido.pedido.data}}</p>
        <p>{{ pedido.pedido.owner}}</p>
        <p>{{ pedido.pedido.id}}</p>

    {% endfor %}


          <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

    <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-4">
                <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->

            <div class="col-lg-4">
                <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h2>Heading</h2>
                <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->

            <div class="col-lg-4">
                <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
    </div><!-- /Container end -->
{%  endblock %}

Hamburgueria/templates/Hamburgueria/pedidos.html
{% extends 'base/base.html' %}
{% load staticfiles%}
{% load static %}

{% block title %} Home {% endblock %}

{% block style %}{% endblock %}

{% block body %}
    {%  include 'base/_navbar.html' %}
    <br><br><br><br>

    <div class="container text-left " >

    {% for pedido in historico %}
        <div class="card">
          <div class="card-header">
              Pedido nº {{ pedido.id }} - Data {{ pedido.data  }}
              <p> Status:     {% if pedido.status_pedido == 'P'%}
                        Pedido Efetuado
                    {% elif pedido.status_pedido == 'A'%}
                        Pedido em Andamento
                    {% elif pedido.status_pedido == 'E'%}
                        Pedido em Entrega
                    {% else %}
                        Entregue
                    {% endif %}</p>
          </div>
          <div class="card-body">
                <p class="card-text">

                    <ul class="list-group">
                        {% for item in produtos %}
                            {% if item.pedido.id == pedido.id %}
                            <li class="list-group-item">
                                 {{ item.produto }}  {{ item.qtd }} unidades.
                            </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </p>
          {% if pedido.status_pedido == 'P' %}
                <a href="{% url 'ham:cancela' pk=pedido.id %}" class="text-right btn btn-danger  ">Editar</a>
          {% endif %}
          </div>
        </div>

    <br>

    {% empty %}
        Sorry, no athletes in this list.
    {% endfor %}

    </div><!-- /Container end -->
{%  endblock %}

templates/base/_footer.html
{#<footer class="container">#}
{#    <p class="float-right"><a href="#">Back to top</a></p>#}
{#    <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>#}
{#</footer>#}

templates/base/_navbar.html
 <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'ham:home' %}" style='font-family: "Droid Serif", "DejaVu Serif", "STIX", serif;'>VH</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            {% if staff %}
              <li class="nav-item active">
              <a class="nav-link" href="/admin/">Administração <span class="sr-only">(current)</span></a>
                </li>
            {% endif %}

            {% if usr and not staff %}
              <a class="nav-link" href="{% url 'ham:pedidos' %}">Meus Pedidos <span class="sr-only"></span></a>
            {% endif %}
          </ul>

        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" style="margin-right: 10px">
            Carrinho <span class="badge badge-light">{{ carrinho | default_if_none:"0"}}</span>
        </button>

            {% if usr %}
                <a class="btn btn-outline-primary" href="{% url 'logout' %}">Sair</a>
            {% else %}
                <a class="btn btn-outline-primary" href="{% url 'login' %}">Entrar</a>
            {% endif %}

        </div>
      </nav>
    </header>

<!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Carrinho</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Quantidade</th>
      <th scope="col">Preço</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

  {% for item in listaCarrinho %}
            <tr>
              <th scope="row">*</th>
              <td>{{item.produto}}</td>
              <td>{{item.qtd }}</td>
              <td>{{item.produto.preco}}</td>
              <td>
                <button type="button" class="btn btn-danger"><a class="btn-danger" href="{% url 'ham:remove' pk=item.produto.id %}">remover</a></button>
              </td>
            </tr>
        {% empty %}
            <p> Nenhum item adicionado ao carrinho</p>
        {% endfor %}
  </tbody>
</table>







      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        <button type="button" class="btn btn-primary" ><a class=" btn-primary" href="{% url 'ham:finaliza' %}">Finalizar Pedido</a></button>
      </div>
    </div>
  </div>
</div>

templates/base/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block style %}{% endblock %}


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Valbernielson's Hamburgueria -{% block title %}{% endblock %}</title>

  </head>

  <body class="text-center">
    {% block body %}{% endblock %}

    {%  include 'base/_footer.html' %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>